@startuml abrirPlantas

skinparam linetype polyline

state in1 as "UNIVERSIDAD_DISPONIBLE"
in1 -[#green]-> abrirPlantas
state in2 as "PLANTA_ABIERTO"
in2 -[#green]-> abrirPlantas

state abrirPlantas as "abrirPlantas()" {

    state " " as MostrandoLista
    state " " as FiltrandoLista

    [*] -[#green]-> MostrandoLista 
    note on link
    <b>Administrador</b> solicita abrir plantas
    end note    
    
    MostrandoLista -[#green]-> FiltrandoLista
    note on link
    <b>Sistema</b> presenta lista de plantas
    • ID y nombre de cada planta
    • Permite solicitar filtrar lista
    • Permite solicitar crear planta nueva
    • Permite solicitar eliminar planta
    • Permite solicitar editar planta
    end note
    
    FiltrandoLista -[#green]-> FiltrandoLista
    note on link
    <b>Administrador</b> solicita filtrar lista
    <b>Sistema</b> presenta lista filtrada
    end note
    
    FiltrandoLista -[#green]-> [*]
    note on link
    <b>Administrador</b> solicita una de las opciones
    end note
}

abrirPlantas -[#green]-> PLANTA_ABIERTO
note on link
editarPlanta()
end note

abrirPlantas -[#green]-> PLANTA_ABIERTO
note on link
crearPlanta()
end note

abrirPlantas -[#green]-> PLANTAS_ABIERTO
note on link
eliminarPlanta()
end note

abrirPlantas -[#green]-> UNIVERSIDAD_DISPONIBLE
note on link
completarGestion()
end note

@enduml
