@startuml
skinparam style strictuml
skinparam sequenceMessageAlign center

boundary "SeleccionarRecorridoView" as view <<boundary>> #629EF9
control "NavegacionController" as controller <<control>> #b5bd68
entity "RecorridoRepository" as repo <<entity>> #F2AC4E
entity "Recorrido" as model <<entity>> #F2AC4E

state ":Recorrido Abierto" as state1 <<collaboration>> #CDEBA5

state1 -> view : seleccionarRecorrido()
view -> controller : procesarSeleccionarRecorrido()
controller -> repo : consultarDatos()
repo --> controller : datos
controller --> view : render()
view -> state1 : <<include>>

@enduml
